### ISSUE TITLE
main 실행 에러 관련

### ISSUE THREAD

**Issue by tmchojo** [L1nked2/LostarkDPM#43]
```
Traceback (most recent call last):
  File "LostarkDPM/main.py", line 4, in <module>
    from src.layers.dynamic.dpm_simulator import DpmSimulator
  File "LostarkDPM/src/layers/dynamic/dpm_simulator.py", line 6, in <module>
    from .buff_manager import BuffManager
  File "LostarkDPM/src/layers/dynamic/buff_manager.py", line 10, in <module>
    class BuffManager():
  File "LostarkDPM/src/layers/dynamic/buff_manager.py", line 52, in BuffManager
    def get_buff(self, buff_name) -> StatBuff | DamageBuff | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
위와 같은 에러가 발생해요

**Comment by L1nked2** [comment]
python 3.10 이상부터 type과 type의 | 연산자가 지원됩니다. python 버전을 3.10 이상으로 업데이트 하시고 사용하시길 바랍니다.
